version: '3.8'

services:
  espaoilserver:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    container_name: espaoilserver
    ports:
      - "8080:8080"
    networks:
      - coolify

networks:
  coolify:
    external: true
