FROM gradle:7-jdk17 AS build
COPY --chown=gradle:gradle . /home/gradle/src
WORKDIR /home/gradle/src
# Ejecutamos shadowJar
RUN gradle shadowJar --no-daemon

FROM eclipse-temurin:17-jre
WORKDIR /app
COPY --from=build /home/gradle/src/app/build/libs/*-all.jar /app/espaoil-server.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/espaoil-server.jar"]
