FROM --platform=linux/amd64 gradle:7-jdk17-alpine AS build
WORKDIR /home/gradle/src
COPY --chown=gradle:gradle . .
RUN gradle shadowJar --no-daemon

FROM --platform=linux/amd64 eclipse-temurin:17-jdk-alpine
WORKDIR /app
COPY --from=build /home/gradle/src/app/build/libs/*-all.jar /app/espaoil-server.jar
EXPOSE 8080
ENTRYPOINT ["java","-jar","/app/espaoil-server.jar"]
